from sqlalchemy import Column, Integer, String, Float, SmallInteger
from sqlalchemy.orm import declarative_base

Base = declarative_base()

class Case(Base):
    __tablename__ = 'case'
    id = Column(Integer, primary_key=True)
    name = Column(String(200))
    price = Column(Integer)
    link = Column(String(500), nullable=False)
    company = Column(String(30), nullable=False)
    product_seq = Column(Integer, nullable=False)
    image = Column(String(500), comment='이미지 링크')
    category = Column(String(20), nullable=False)
    size = Column(String(20), nullable=False)
    power_included = Column(String(15))
    power_support = Column(String(30), comment='호환성')
    board_support = Column(Integer, nullable=False, comment='호환성, 비트마스킹')
    bay_133 = Column(SmallInteger, comment='단위: 개')
    bay_89 = Column(SmallInteger, comment='단위: 개')
    bay_64 = Column(SmallInteger, comment='단위: 개')
    pci_horizontal = Column(SmallInteger, comment='단위: 개')
    pci_vertical = Column(SmallInteger, comment='단위: 개')
    cooling_fan = Column(SmallInteger, comment='총 n개')
    led_fan = Column(SmallInteger, default=None, comment='개')
    front_type = Column(String(10))
    side_open = Column(String(10))
    side_type = Column(String(10))
    back_vent = Column(String(30))
    front_vent = Column(String(30))
    top_vent = Column(String(30))
    bottom_vent = Column(String(30))
    external_port = Column(Integer, comment='비트마스킹')
    width = Column(Float, comment='mm, 호환성')
    height = Column(Float, comment='mm, 호환성')
    depth = Column(Float, comment='mm, 호환성')
    gpu_size = Column(Integer, comment='mm, 호환성')
    cpu_cooler_size = Column(Integer, comment='mm, 호환성')
    power_size = Column(Integer, comment='mm, 호환성')
    liquid_cooler = Column(SmallInteger, default=None, comment='최대 n열 지원, 호환성')
    radiator_top = Column(Integer, default=None, comment='mm, 호환성')
    radiator_front = Column(Integer, default=None, comment='mm, 호환성')
    radiator_rear = Column(Integer, default=None, comment='mm, 호환성')
    radiator_side = Column(Integer, default=None, comment='mm, 호환성')
    feature = Column(Integer, comment='비트마스킹')
    led_color = Column(String(10))
    reg_date = Column(Integer, comment='yyyymm')
    bookmark = Column(Integer, default=0)
